obj-$(CONFIG_TEST_HELLO)	+= test-hello/hello.o

obj-$(CONFIG_TEST_PGTABLE)	+= test-pgtable/pgtable.o

obj-$(CONFIG_TEST_PAGEWALK)	+= test-pagewalk/pagewalk.o

obj-$(CONFIG_TEST_FIXMAP)	+= test-fixmap/fixmap.o

obj-$(CONFIG_TEST_MEMBLOCK)	+= test-memblock/memblock.o

obj-$(CONFIG_TEST_PARAMS)	+= test-params/params.o

obj-$(CONFIG_TEST_OOPS)		+= test-oops/oops.o

obj-$(CONFIG_TEST_MEMCONV)	+= test-memconv/memconv.o

obj-$(CONFIG_TEST_KALLSYMS)	+= test-kallsyms/kallsyms.o

obj-$(CONFIG_TEST_FILESYSTEM)	+= test-filesystem/filesystem.o

obj-$(CONFIG_TEST_RCU)		+= test-rcu/rcu.o

obj-$(CONFIG_TEST_PROCFS)	+= test-procfs/procfs.o

obj-$(CONFIG_TEST_DEBUGFS)	+= test-debugfs/debugfs.o

obj-$(CONFIG_TEST_SYSFS)	+= test-sysfs/sysfs.o

obj-$(CONFIG_TEST_KOBJECT)	+= test-kobject/kobject.o