obj-$(CONFIG_TEST_MODULES) += test-hello/hello.o
obj-$(CONFIG_TEST_MODULES) += test-pgtable/pgtable.o
obj-$(CONFIG_TEST_MODULES) += test-pagewalk/pagewalk.o
obj-$(CONFIG_TEST_MODULES) += test-fixmap/fixmap.o